/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Rattler */

#ifndef _Included_Rattler
#define _Included_Rattler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Rattler
 * Method:    create
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_Rattler_create
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
