/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mamba_rattler_Rattler */

#ifndef _Included_org_mamba_rattler_Rattler
#define _Included_org_mamba_rattler_Rattler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mamba_rattler_Rattler
 * Method:    create
 * Signature: (Lorg/mamba/rattler/CreateOpts;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mamba_rattler_Rattler_create
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
